### ISSUE TITLE
Mod breaks material tooltip material conversion

### ISSUE THREAD

**Issue by GabrielSerealia** [badhaloninja/MaterialTipAutoScoop#1]
When using the mod I found that I was not able to convert or bulk convert materials to another type
It would result in generating a blank new material orb of that type
As a test I removed the mod and the functionality started to work again
I have not tested the mod on its own

On windows 11
Latest neos version (steam)

**Comment by badhaloninja** [comment]
Fixed in [version v1.2.1](https://github.com/badhaloninja/MaterialTipAutoScoop/releases/tag/v1.2.1)
